apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsession
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsession
  template:
    metadata:
      labels:
        app: dsession
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: redis:5-alpine
        name: redis
        resources: {}
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
      - image: sagadash/grpc-web-proxy
        args: [ 
          "--run_tls_server=false",
          "--backend_addr=dsession:50051",
          "--backend_max_call_recv_msg_size=5242880",
          "--allow_all_origins"
        ]
        name:  webproxy
        resources: {}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
      - image: hobord/dsession
        imagePullPolicy: Always
        name: dsession
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
        resources: {}
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dsession
spec:
  selector:
    app: dsession
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  - name: redis
    protocol: TCP
    port: 6379
  type: NodePort
  
---
